apiVersion: v1
kind: Service
metadata:
  name: aws-dms-task-status-exporter
  labels:
    app: aws-dms-task-status-exporter
spec:
  ports:
    - port: 9213
      targetPort: 9213
  selector:
    app: aws-dms-task-status-exporter
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aws-dms-task-status-exporter
spec:
  selector:
    matchLabels:
      run: aws-dms-task-status-exporter
  replicas: 2
  template:
    metadata:
      labels:
        run: aws-dms-task-status-exporter
    spec:
      containers:
      - name: aws-dms-task-status-exporter
        image: 476023098245.dkr.ecr.us-east-1.amazonaws.com/aws_dms_task_status_reporter:IMAGE_TAG
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: 9213
      imagePullSecrets:
      - name: ecr